load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "compile",
    srcs = ["compile.go"],
    importpath = "github.com/tejaspanse/cinegram/pkg/compile",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/ast",
        "//pkg/diag",
        "//pkg/emit/mermaid",
        "//pkg/ir",
        "//pkg/loader",
        "//pkg/symbol",
        "//pkg/units",
    ],
)

go_test(
    name = "compile_test",
    srcs = ["compile_test.go"],
    data = glob(["testdata/**"]),
    embed = [":compile"],
    deps = [
        "//pkg/ir",
        "//pkg/parser",
    ],
)
