load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "registry",
    srcs = ["registry.go"],
    importpath = "github.com/tejaspanse/cinegram/pkg/registry",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/ast",
        "//pkg/diag",
        "//pkg/source",
        "//pkg/symbol",
    ],
)
