load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mermaid",
    srcs = ["mermaid.go"],
    importpath = "github.com/tejaspanse/diagramator/pkg/emit/mermaid",
    visibility = ["//visibility:public"],
    deps = ["//pkg/ast"],
)

go_test(
    name = "mermaid_test",
    srcs = ["mermaid_test.go"],
    deps = [
        ":mermaid",
        "//pkg/parser",
    ],
)
