load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "vsix_lib",
    srcs = ["main.go"],
    importpath = "github.com/tejaspanse/cinegram/cmd/vsix",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "vsix",
    embed = [":vsix_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "vsix_test",
    srcs = ["main_test.go"],
    embed = [":vsix_lib"],
)
